### ISSUE TITLE
Assets could not be loaded

### ISSUE THREAD

**Issue by muaddib1201** [Nikke-db/spine-web-player-template#1]
Please help, I don’t understand spine at all.

Error: Assets could not be loaded.{"/assets/neon/neon.skel":"Couldn't load binary /assets/neon/neon.skel: status 404, [object ArrayBuffer]","/assets/neon/neon.atlas":"Couldn't load texture atlas /assets/neon/neon.atlas: status 404, <!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot GET /assets/neon/neon.atlas</pre>\n</body>\n</html>\n"}

**Comment by muaddib1201** [comment]
Following the instructions, I used the Live Server extension in Visual Studio Code.

**Comment by Nikke-db** [comment]
I have freshly cloned the repository on my professional laptop and everything is working, did you change anything in the code, or neon assets?

**Comment by Nikke-db** [comment]
closed for inactivity
