### ISSUE TITLE
Region not found in atlas

### ISSUE THREAD

**Issue by KISGP** [Nikke-db/spine-web-player-template#3]
I would like to understand why the spine-player (version 4.1) I compiled from official code is not running properly.

I have copied the files neon.skel, neon.atlas, and neon.png into the assets folder. In the official example.html, I only modified the skelUrl and atlasUrl. However, when I open it with a live server, the screen displays "Could not load skeleton binary," and the console shows "Uncaught Error: Region not found in atlas: null (region attachment: null)."

![PixPin_2024-05-01_16-45-26](https://github.com/Nikke-db/spine-web-player-template/assets/88269600/38d948ab-136c-4d57-8b3a-dc6dbf653867)

![PixPin_2024-05-01_16-43-19](https://github.com/Nikke-db/spine-web-player-template/assets/88269600/b60ce9ce-2716-4868-89a8-03ec62a3d74c)

I am unsure what is causing this issue—whether it stems from the code or the Spine version. For reference, the spine-web-player-template runs smoothly. Here is a screenshot of it in operation.

![PixPin_2024-05-01_16-49-09](https://github.com/Nikke-db/spine-web-player-template/assets/88269600/c1811b28-5a9e-4050-95d3-d0209b0e8cd4)

**Comment by Koshirei** [comment]
can you send me the project as a zip or make a repository so I take a deeper look at which spine runtime you have or neon files themselves?

**Comment by KISGP** [comment]
> can you send me the project as a zip or make a repository so I take a deeper look at which spine runtime you have or neon files themselves?

Sorry to bother you.This error occurred because I mistakenly identified the 4.0 code as being the 4.1 code.😵‍💫

![PixPin_2024-05-01_23-52-32](https://github.com/Nikke-db/spine-web-player-template/assets/88269600/b258084f-a8e6-4e22-8eb2-c00bbb652829)

**Comment by KISGP** [comment]
Now, I am able to run the code normally using the 4.1 version.
